<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I913D3N" failures="0" tests="2" name="Default test" time="7.462" errors="0" timestamp="2021-02-19T18:35:40 CST">
  <testcase classname="test.czh.runcase.LoginCase" name="@BeforeClass beforeClass" time="7.409">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;test.czh.page.FirstPage.GetExhibitionInputElement()&amp;quot; because &amp;quot;this.firstpage&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "test.czh.page.FirstPage.GetExhibitionInputElement()" because "this.firstpage" is null
at test.czh.handle.LoginHandle.SendExhibitionInput(LoginHandle.java:48)
at test.czh.runcase.LoginCase.beforeClass(LoginCase.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass beforeClass -->
  <testcase classname="test.czh.runcase.LoginCase" name="@AfterMethod afterMethod" time="-1.613730940283E9">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase classname="test.czh.runcase.LoginCase" name="@AfterMethod afterMethod" time="-1.61373094029E9">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase classname="test.czh.runcase.LoginCase" name="@AfterClass afterClass" time="-1.613730940292E9">
    <skipped/>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase classname="test.czh.runcase.LoginCase" name="TestLoginSucccess" time="0.0">
    <skipped/>
  </testcase> <!-- TestLoginSucccess -->
  <testcase classname="test.czh.runcase.LoginCase" name="TestLoginuserError" time="0.0">
    <skipped/>
  </testcase> <!-- TestLoginuserError -->
</testsuite> <!-- Default test -->
